-- Add global topics and link terms/formulas to one topic by topic_handle.

CREATE TABLE IF NOT EXISTS tbl_topic (
  topic_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_name VARCHAR(200) NOT NULL,
  topic_handle VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tbl_topic_handle
  ON tbl_topic(topic_handle);

CREATE INDEX IF NOT EXISTS idx_tbl_topic_name
  ON tbl_topic(topic_name);

ALTER TABLE tbl_formula
  ADD COLUMN IF NOT EXISTS topic_handle VARCHAR(100) NULL;

ALTER TABLE tbl_term
  ADD COLUMN IF NOT EXISTS topic_handle VARCHAR(100) NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE table_name = 'tbl_formula'
      AND constraint_name = 'fk_tbl_formula_topic_handle'
  ) THEN
    ALTER TABLE tbl_formula
      ADD CONSTRAINT fk_tbl_formula_topic_handle
      FOREIGN KEY (topic_handle) REFERENCES tbl_topic(topic_handle) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE table_name = 'tbl_term'
      AND constraint_name = 'fk_tbl_term_topic_handle'
  ) THEN
    ALTER TABLE tbl_term
      ADD CONSTRAINT fk_tbl_term_topic_handle
      FOREIGN KEY (topic_handle) REFERENCES tbl_topic(topic_handle) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_tbl_formula_topic_handle
  ON tbl_formula(topic_handle);

CREATE INDEX IF NOT EXISTS idx_tbl_term_topic_handle
  ON tbl_term(topic_handle);

COMMENT ON TABLE tbl_topic IS 'Global topic catalog used to group terms and formulas for exam sheets.';
COMMENT ON COLUMN tbl_topic.topic_name IS 'Display name for topic section headings.';
COMMENT ON COLUMN tbl_topic.topic_handle IS 'Stable unique slug for imports and references.';
COMMENT ON COLUMN tbl_formula.topic_handle IS 'Optional topic handle reference used by exam sheet grouping.';
COMMENT ON COLUMN tbl_term.topic_handle IS 'Optional topic handle reference used by exam sheet grouping.';
