-- Migration: Add constants and units tables
-- Creates: tbl_constant, tbl_unit
--
-- Constants: mathematical/physical constants (pi, e, c, Boltzmann, Planck)
-- Units: measurement units (SI base units, etc.)

-- ============================================================================
-- 1. tbl_constant
-- ============================================================================

CREATE TABLE IF NOT EXISTS tbl_constant (
  constant_id     INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  constant_name   VARCHAR(200) NOT NULL,
  symbol          VARCHAR(100) NULL,
  value_text      TEXT NULL,
  description     TEXT NULL,
  display_order   INTEGER NULL,
  created_at      TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tbl_constant_display_order ON tbl_constant(display_order);
CREATE INDEX IF NOT EXISTS idx_tbl_constant_name ON tbl_constant(constant_name);

COMMENT ON TABLE tbl_constant IS 'Mathematical and physical constants (pi, e, c, Boltzmann, Planck, etc.)';

-- ============================================================================
-- 2. tbl_unit
-- ============================================================================

CREATE TABLE IF NOT EXISTS tbl_unit (
  unit_id         INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_name       VARCHAR(200) NOT NULL,
  symbol          VARCHAR(50) NULL,
  unit_system     VARCHAR(50) NULL,
  description     TEXT NULL,
  display_order   INTEGER NULL,
  created_at      TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tbl_unit_display_order ON tbl_unit(display_order);
CREATE INDEX IF NOT EXISTS idx_tbl_unit_name ON tbl_unit(unit_name);

COMMENT ON TABLE tbl_unit IS 'Measurement units (SI base units, etc.)';
