-- Canonical terms and formulas per catalog course, with optional segment.
-- Admin maintains these on the course-templates setup page. Keyed by catalog course only
-- (not custom courses or personal projects). Run after add_catalog_course_tables.sql.

-- 1. tbl_catalog_course_term
CREATE TABLE IF NOT EXISTS tbl_catalog_course_term (
  catalog_course_term_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  catalog_course_id      INTEGER NOT NULL,
  term_id                INTEGER NOT NULL,
  segment_label          VARCHAR(255) NULL,
  display_order          INTEGER NULL DEFAULT 0,
  created_at             TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_catalog_course_term_catalog_fkey
    FOREIGN KEY (catalog_course_id) REFERENCES tbl_catalog_course(catalog_course_id) ON DELETE CASCADE,
  CONSTRAINT tbl_catalog_course_term_term_fkey
    FOREIGN KEY (term_id) REFERENCES tbl_term(term_id) ON DELETE CASCADE
);

-- Same term can appear in different segments; one row per (catalog_course_id, term_id, segment_label)
CREATE UNIQUE INDEX IF NOT EXISTS idx_tbl_catalog_course_term_uniq
  ON tbl_catalog_course_term (catalog_course_id, term_id, COALESCE(segment_label, ''));

CREATE INDEX IF NOT EXISTS idx_tbl_catalog_course_term_catalog ON tbl_catalog_course_term(catalog_course_id);
CREATE INDEX IF NOT EXISTS idx_tbl_catalog_course_term_term ON tbl_catalog_course_term(term_id);

COMMENT ON TABLE tbl_catalog_course_term IS 'Canonical terms per catalog course and segment; admin-maintained template.';
COMMENT ON COLUMN tbl_catalog_course_term.segment_label IS 'Segment (e.g. Chapter 3); NULL = full course.';

-- 2. tbl_catalog_course_formula
CREATE TABLE IF NOT EXISTS tbl_catalog_course_formula (
  catalog_course_formula_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  catalog_course_id         INTEGER NOT NULL,
  formula_id               INTEGER NOT NULL,
  segment_label            VARCHAR(255) NULL,
  display_order            INTEGER NULL DEFAULT 0,
  created_at               TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_catalog_course_formula_catalog_fkey
    FOREIGN KEY (catalog_course_id) REFERENCES tbl_catalog_course(catalog_course_id) ON DELETE CASCADE,
  CONSTRAINT tbl_catalog_course_formula_formula_fkey
    FOREIGN KEY (formula_id) REFERENCES tbl_formula(formula_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tbl_catalog_course_formula_uniq
  ON tbl_catalog_course_formula (catalog_course_id, formula_id, COALESCE(segment_label, ''));

CREATE INDEX IF NOT EXISTS idx_tbl_catalog_course_formula_catalog ON tbl_catalog_course_formula(catalog_course_id);
CREATE INDEX IF NOT EXISTS idx_tbl_catalog_course_formula_formula ON tbl_catalog_course_formula(formula_id);

COMMENT ON TABLE tbl_catalog_course_formula IS 'Canonical formulas per catalog course and segment; admin-maintained template.';
COMMENT ON COLUMN tbl_catalog_course_formula.segment_label IS 'Segment (e.g. Chapter 3); NULL = full course.';
