-- Password reset tokens for forgot-password flow.
-- Run after add_user_table.sql

CREATE TABLE IF NOT EXISTS tbl_password_reset (
  id          INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email       VARCHAR(255) NOT NULL,
  token_lookup VARCHAR(64) NOT NULL,
  token_hash  VARCHAR(255) NOT NULL,
  expires_at  TIMESTAMP NOT NULL,
  created_at  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_password_reset_token_lookup_uniq UNIQUE (token_lookup)
);

CREATE INDEX IF NOT EXISTS idx_tbl_password_reset_email ON tbl_password_reset(email);
CREATE INDEX IF NOT EXISTS idx_tbl_password_reset_expires ON tbl_password_reset(expires_at);

COMMENT ON TABLE tbl_password_reset IS 'One-time tokens for password reset; token_lookup is sha256 for lookup, token_hash is bcrypt for verification.';
