-- Introduce tbl_segment and replace segment_label with segment_id everywhere.
-- Run after add_catalog_course_term_formula_tables.sql, add_exam_sheet_template_tables.sql,
-- add_exam_sheet_template_catalog_course_id.sql, add_user_course_term.sql, add_course_formula_segment.sql.

-- 1. Create tbl_segment
CREATE TABLE IF NOT EXISTS tbl_segment (
  segment_id             INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  catalog_course_id       INTEGER NOT NULL,
  segment_name           VARCHAR(255) NOT NULL,
  segment_handle         VARCHAR(255) NOT NULL,
  course_segment_default BOOLEAN NOT NULL DEFAULT false,
  created_at             TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_segment_catalog_fkey
    FOREIGN KEY (catalog_course_id) REFERENCES tbl_catalog_course(catalog_course_id) ON DELETE CASCADE,
  CONSTRAINT tbl_segment_handle_uniq UNIQUE (catalog_course_id, segment_handle)
);

CREATE INDEX IF NOT EXISTS idx_tbl_segment_catalog ON tbl_segment(catalog_course_id);

COMMENT ON TABLE tbl_segment IS 'Named segments per catalog course (e.g. Midterm 1); replaces free-text segment_label.';
COMMENT ON COLUMN tbl_segment.segment_handle IS 'Slug unique per catalog course, e.g. stat-352-midterm-1.';
COMMENT ON COLUMN tbl_segment.course_segment_default IS 'Reserved for future use.';

-- 2. Populate tbl_segment from distinct (catalog_course_id, segment_label) in catalog term/formula
--    segment_handle = course_handle + '-' + slug(segment_label); dedupe handles per course with -2, -3...
WITH
  course_handles AS (
    SELECT catalog_course_id, COALESCE(NULLIF(TRIM(course_handle), ''), 'course') AS h
    FROM tbl_catalog_course
  ),
  raw_labels AS (
    SELECT DISTINCT catalog_course_id, TRIM(segment_label) AS segment_name
    FROM (
      SELECT catalog_course_id, segment_label FROM tbl_catalog_course_term
      UNION
      SELECT catalog_course_id, segment_label FROM tbl_catalog_course_formula
    ) u
    WHERE segment_label IS NOT NULL AND TRIM(segment_label) <> ''
  ),
  slugged AS (
    SELECT r.catalog_course_id, r.segment_name,
           LOWER(REGEXP_REPLACE(REGEXP_REPLACE(TRIM(r.segment_name), '[^a-zA-Z0-9]+', '-', 'g'), '^-+|-+$', '', 'g')) AS slug
    FROM raw_labels r
  ),
  with_handle_base AS (
    SELECT s.catalog_course_id, s.segment_name,
           COALESCE(NULLIF(TRIM(c.h), ''), 'course') || CASE WHEN s.slug <> '' THEN '-' || s.slug ELSE '' END AS handle_base
    FROM slugged s
    JOIN course_handles c ON c.catalog_course_id = s.catalog_course_id
  ),
  ranked AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY catalog_course_id, handle_base ORDER BY segment_name) AS rn
    FROM with_handle_base
  ),
  with_handle AS (
    SELECT catalog_course_id, segment_name,
           handle_base || CASE WHEN rn > 1 THEN '-' || rn::TEXT ELSE '' END AS segment_handle
    FROM ranked
  )
INSERT INTO tbl_segment (catalog_course_id, segment_name, segment_handle)
SELECT catalog_course_id, segment_name, segment_handle
FROM with_handle
ON CONFLICT (catalog_course_id, segment_handle) DO NOTHING;

-- 3. Add segment_id to all five tables
ALTER TABLE tbl_catalog_course_term
  ADD COLUMN IF NOT EXISTS segment_id INTEGER NULL;
ALTER TABLE tbl_catalog_course_formula
  ADD COLUMN IF NOT EXISTS segment_id INTEGER NULL;
ALTER TABLE tbl_user_course_term
  ADD COLUMN IF NOT EXISTS segment_id INTEGER NULL;
ALTER TABLE tbl_user_course_formula
  ADD COLUMN IF NOT EXISTS segment_id INTEGER NULL;
ALTER TABLE tbl_exam_sheet_template
  ADD COLUMN IF NOT EXISTS segment_id INTEGER NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tbl_catalog_course_term_segment_fkey') THEN
    ALTER TABLE tbl_catalog_course_term ADD CONSTRAINT tbl_catalog_course_term_segment_fkey
      FOREIGN KEY (segment_id) REFERENCES tbl_segment(segment_id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tbl_catalog_course_formula_segment_fkey') THEN
    ALTER TABLE tbl_catalog_course_formula ADD CONSTRAINT tbl_catalog_course_formula_segment_fkey
      FOREIGN KEY (segment_id) REFERENCES tbl_segment(segment_id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tbl_user_course_term_segment_fkey') THEN
    ALTER TABLE tbl_user_course_term ADD CONSTRAINT tbl_user_course_term_segment_fkey
      FOREIGN KEY (segment_id) REFERENCES tbl_segment(segment_id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tbl_user_course_formula_segment_fkey') THEN
    ALTER TABLE tbl_user_course_formula ADD CONSTRAINT tbl_user_course_formula_segment_fkey
      FOREIGN KEY (segment_id) REFERENCES tbl_segment(segment_id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_exam_sheet_template_segment') THEN
    ALTER TABLE tbl_exam_sheet_template ADD CONSTRAINT fk_exam_sheet_template_segment
      FOREIGN KEY (segment_id) REFERENCES tbl_segment(segment_id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_tbl_catalog_course_term_segment ON tbl_catalog_course_term(segment_id);
CREATE INDEX IF NOT EXISTS idx_tbl_catalog_course_formula_segment ON tbl_catalog_course_formula(segment_id);
CREATE INDEX IF NOT EXISTS idx_tbl_user_course_term_segment ON tbl_user_course_term(segment_id);
CREATE INDEX IF NOT EXISTS idx_tbl_user_course_formula_segment ON tbl_user_course_formula(segment_id);
CREATE INDEX IF NOT EXISTS idx_exam_sheet_template_segment ON tbl_exam_sheet_template(segment_id);

-- 4. Backfill segment_id from segment_label

-- Catalog term
UPDATE tbl_catalog_course_term t
SET segment_id = s.segment_id
FROM tbl_segment s
WHERE s.catalog_course_id = t.catalog_course_id
  AND TRIM(COALESCE(t.segment_label, '')) <> ''
  AND s.segment_name = TRIM(t.segment_label)
  AND t.segment_id IS NULL;

-- Catalog formula
UPDATE tbl_catalog_course_formula t
SET segment_id = s.segment_id
FROM tbl_segment s
WHERE s.catalog_course_id = t.catalog_course_id
  AND TRIM(COALESCE(t.segment_label, '')) <> ''
  AND s.segment_name = TRIM(t.segment_label)
  AND t.segment_id IS NULL;

-- User course term (catalog_course_id from tbl_course; subquery to avoid referencing u in FROM)
UPDATE tbl_user_course_term u
SET segment_id = (
  SELECT s.segment_id FROM tbl_segment s
  JOIN tbl_course c ON c.catalog_course_id = s.catalog_course_id AND c.course_id = u.course_id
  WHERE s.segment_name = TRIM(COALESCE(u.segment_label, ''))
  LIMIT 1
)
WHERE u.segment_id IS NULL
  AND TRIM(COALESCE(u.segment_label, '')) <> ''
  AND EXISTS (SELECT 1 FROM tbl_course c WHERE c.course_id = u.course_id AND c.catalog_course_id IS NOT NULL);

-- User course formula
UPDATE tbl_user_course_formula u
SET segment_id = (
  SELECT s.segment_id FROM tbl_segment s
  JOIN tbl_course c ON c.catalog_course_id = s.catalog_course_id AND c.course_id = u.course_id
  WHERE s.segment_name = TRIM(COALESCE(u.segment_label, ''))
  LIMIT 1
)
WHERE u.segment_id IS NULL
  AND TRIM(COALESCE(u.segment_label, '')) <> ''
  AND EXISTS (SELECT 1 FROM tbl_course c WHERE c.course_id = u.course_id AND c.catalog_course_id IS NOT NULL);

-- Exam sheet template (has catalog_course_id and segment_label)
UPDATE tbl_exam_sheet_template t
SET segment_id = s.segment_id
FROM tbl_segment s
WHERE s.catalog_course_id = t.catalog_course_id
  AND t.catalog_course_id IS NOT NULL
  AND TRIM(COALESCE(t.segment_label, '')) <> ''
  AND s.segment_name = TRIM(t.segment_label)
  AND t.segment_id IS NULL;

-- 5. Drop old unique indexes that use segment_label
DROP INDEX IF EXISTS idx_tbl_catalog_course_term_uniq;
DROP INDEX IF EXISTS idx_tbl_catalog_course_formula_uniq;
DROP INDEX IF EXISTS idx_exam_sheet_template_scope;

-- 6. Create new unique indexes using segment_id
CREATE UNIQUE INDEX IF NOT EXISTS idx_tbl_catalog_course_term_uniq
  ON tbl_catalog_course_term (catalog_course_id, term_id, COALESCE(segment_id, 0));
CREATE UNIQUE INDEX IF NOT EXISTS idx_tbl_catalog_course_formula_uniq
  ON tbl_catalog_course_formula (catalog_course_id, formula_id, COALESCE(segment_id, 0));
CREATE UNIQUE INDEX IF NOT EXISTS idx_exam_sheet_template_scope
  ON tbl_exam_sheet_template(course_id, COALESCE(segment_id, 0));

-- 7. Drop segment_label (and segment_type from user term if still present)
ALTER TABLE tbl_catalog_course_term   DROP COLUMN IF EXISTS segment_label;
ALTER TABLE tbl_catalog_course_formula DROP COLUMN IF EXISTS segment_label;
ALTER TABLE tbl_user_course_term      DROP COLUMN IF EXISTS segment_label;
ALTER TABLE tbl_user_course_term      DROP COLUMN IF EXISTS segment_type;
ALTER TABLE tbl_user_course_formula   DROP COLUMN IF EXISTS segment_label;
ALTER TABLE tbl_exam_sheet_template  DROP COLUMN IF EXISTS segment_label;

COMMENT ON COLUMN tbl_catalog_course_term.segment_id IS 'Optional segment (e.g. Midterm 1); NULL = full course.';
COMMENT ON COLUMN tbl_catalog_course_formula.segment_id IS 'Optional segment; NULL = full course.';
COMMENT ON COLUMN tbl_user_course_term.segment_id IS 'Optional segment; NULL = full course.';
COMMENT ON COLUMN tbl_user_course_formula.segment_id IS 'Optional segment; NULL = full course.';
COMMENT ON COLUMN tbl_exam_sheet_template.segment_id IS 'Optional segment; NULL = full course.';
