-- Institutions, courses, user-course enrollment, and user-course-formula links.
-- Run after add_user_table.sql. No term/year on course per product decision.
-- tbl_user_course_formula has FK to tbl_user_course so user must be enrolled before adding formulas.

-- 1. tbl_institution
CREATE TABLE IF NOT EXISTS tbl_institution (
  institution_id   INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution_name VARCHAR(255) NOT NULL,
  institution_handle VARCHAR(100) NULL,
  country          VARCHAR(100) NULL,
  region           VARCHAR(100) NULL,
  created_at       TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_institution_handle_uniq UNIQUE (institution_handle)
);

CREATE INDEX IF NOT EXISTS idx_tbl_institution_handle ON tbl_institution(institution_handle);
CREATE INDEX IF NOT EXISTS idx_tbl_institution_name ON tbl_institution(institution_name);

COMMENT ON TABLE tbl_institution IS 'Schools/organizations; standardized list for courses.';

-- 2. tbl_course (no term/year)
CREATE TABLE IF NOT EXISTS tbl_course (
  course_id     INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_name   VARCHAR(255) NOT NULL,
  course_code   VARCHAR(50) NULL,
  institution_id INTEGER NULL,
  course_type   VARCHAR(20) NULL,
  created_at    TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_course_institution_fkey
    FOREIGN KEY (institution_id) REFERENCES tbl_institution(institution_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_tbl_course_institution ON tbl_course(institution_id);
CREATE INDEX IF NOT EXISTS idx_tbl_course_name ON tbl_course(course_name);

COMMENT ON TABLE tbl_course IS 'Course or learning project; institution_id NULL for personal.';

-- 3. tbl_user_course
CREATE TABLE IF NOT EXISTS tbl_user_course (
  user_id    INTEGER NOT NULL,
  course_id  INTEGER NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, course_id),
  CONSTRAINT tbl_user_course_user_fkey
    FOREIGN KEY (user_id) REFERENCES tbl_user(user_id) ON DELETE CASCADE,
  CONSTRAINT tbl_user_course_course_fkey
    FOREIGN KEY (course_id) REFERENCES tbl_course(course_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_tbl_user_course_user ON tbl_user_course(user_id);
CREATE INDEX IF NOT EXISTS idx_tbl_user_course_course ON tbl_user_course(course_id);

COMMENT ON TABLE tbl_user_course IS 'User enrollments in courses (many-to-many).';

-- 4. tbl_user_course_formula (FK to enrollment so must be enrolled before adding formulas)
CREATE TABLE IF NOT EXISTS tbl_user_course_formula (
  user_id       INTEGER NOT NULL,
  course_id     INTEGER NOT NULL,
  formula_id    INTEGER NOT NULL,
  display_order INTEGER NULL DEFAULT 0,
  created_at    TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, course_id, formula_id),
  CONSTRAINT tbl_user_course_formula_enrollment_fkey
    FOREIGN KEY (user_id, course_id) REFERENCES tbl_user_course(user_id, course_id) ON DELETE CASCADE,
  CONSTRAINT tbl_user_course_formula_formula_fkey
    FOREIGN KEY (formula_id) REFERENCES tbl_formula(formula_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_tbl_user_course_formula_user_course ON tbl_user_course_formula(user_id, course_id);
CREATE INDEX IF NOT EXISTS idx_tbl_user_course_formula_formula ON tbl_user_course_formula(formula_id);

COMMENT ON TABLE tbl_user_course_formula IS 'Formulas linked to a user course; requires enrollment (tbl_user_course).';
