-- Exam-sheet template and user configuration tables.
-- Uses handles for cross-environment portability.

CREATE TABLE IF NOT EXISTS tbl_exam_sheet_template (
  template_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL,
  segment_label VARCHAR(255) NULL,
  template_name VARCHAR(255) NULL,
  created_by_user_id INTEGER NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_exam_sheet_template_course
    FOREIGN KEY (course_id) REFERENCES tbl_course(course_id) ON DELETE CASCADE,
  CONSTRAINT fk_exam_sheet_template_user
    FOREIGN KEY (created_by_user_id) REFERENCES tbl_user(user_id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_exam_sheet_template_scope
  ON tbl_exam_sheet_template(course_id, COALESCE(segment_label, ''));

CREATE TABLE IF NOT EXISTS tbl_exam_sheet_template_topic (
  template_topic_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id INTEGER NOT NULL,
  topic_handle VARCHAR(100) NOT NULL,
  topic_order INTEGER NOT NULL DEFAULT 0,
  include_flag BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_exam_sheet_template_topic_template
    FOREIGN KEY (template_id) REFERENCES tbl_exam_sheet_template(template_id) ON DELETE CASCADE,
  CONSTRAINT fk_exam_sheet_template_topic_handle
    FOREIGN KEY (topic_handle) REFERENCES tbl_topic(topic_handle) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_exam_sheet_template_topic_unique
  ON tbl_exam_sheet_template_topic(template_id, topic_handle);

CREATE INDEX IF NOT EXISTS idx_exam_sheet_template_topic_order
  ON tbl_exam_sheet_template_topic(template_id, topic_order);

CREATE TABLE IF NOT EXISTS tbl_exam_sheet_template_item (
  template_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id INTEGER NOT NULL,
  item_type VARCHAR(20) NOT NULL,
  item_handle VARCHAR(100) NOT NULL,
  topic_handle VARCHAR(100) NULL,
  item_order INTEGER NOT NULL DEFAULT 0,
  include_flag BOOLEAN NOT NULL DEFAULT true,
  worked_example_mode VARCHAR(20) NOT NULL DEFAULT 'auto',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_exam_sheet_template_item_template
    FOREIGN KEY (template_id) REFERENCES tbl_exam_sheet_template(template_id) ON DELETE CASCADE,
  CONSTRAINT fk_exam_sheet_template_item_topic
    FOREIGN KEY (topic_handle) REFERENCES tbl_topic(topic_handle) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_exam_sheet_template_item_type
    CHECK (item_type IN ('term', 'formula')),
  CONSTRAINT chk_exam_sheet_template_item_worked_example_mode
    CHECK (worked_example_mode IN ('auto', 'always', 'never'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_exam_sheet_template_item_unique
  ON tbl_exam_sheet_template_item(template_id, item_type, item_handle);

CREATE INDEX IF NOT EXISTS idx_exam_sheet_template_item_order
  ON tbl_exam_sheet_template_item(template_id, item_type, item_order);

CREATE TABLE IF NOT EXISTS tbl_exam_sheet_user_config (
  user_config_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  template_id INTEGER NOT NULL,
  margin_mm INTEGER NULL,
  column_gap_px INTEGER NULL,
  font_scale_pct INTEGER NULL,
  line_spacing_pct INTEGER NULL,
  compact_mode BOOLEAN NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_exam_sheet_user_config_user
    FOREIGN KEY (user_id) REFERENCES tbl_user(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_exam_sheet_user_config_template
    FOREIGN KEY (template_id) REFERENCES tbl_exam_sheet_template(template_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_exam_sheet_user_config_unique
  ON tbl_exam_sheet_user_config(user_id, template_id);

CREATE TABLE IF NOT EXISTS tbl_exam_sheet_user_topic_override (
  user_topic_override_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_config_id INTEGER NOT NULL,
  topic_handle VARCHAR(100) NOT NULL,
  topic_order INTEGER NULL,
  include_flag BOOLEAN NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_exam_sheet_user_topic_override_config
    FOREIGN KEY (user_config_id) REFERENCES tbl_exam_sheet_user_config(user_config_id) ON DELETE CASCADE,
  CONSTRAINT fk_exam_sheet_user_topic_override_handle
    FOREIGN KEY (topic_handle) REFERENCES tbl_topic(topic_handle) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_exam_sheet_user_topic_override_unique
  ON tbl_exam_sheet_user_topic_override(user_config_id, topic_handle);

CREATE TABLE IF NOT EXISTS tbl_exam_sheet_user_item_override (
  user_item_override_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_config_id INTEGER NOT NULL,
  item_type VARCHAR(20) NOT NULL,
  item_handle VARCHAR(100) NOT NULL,
  topic_handle VARCHAR(100) NULL,
  item_order INTEGER NULL,
  include_flag BOOLEAN NULL,
  worked_example_mode VARCHAR(20) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_exam_sheet_user_item_override_config
    FOREIGN KEY (user_config_id) REFERENCES tbl_exam_sheet_user_config(user_config_id) ON DELETE CASCADE,
  CONSTRAINT fk_exam_sheet_user_item_override_topic
    FOREIGN KEY (topic_handle) REFERENCES tbl_topic(topic_handle) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_exam_sheet_user_item_override_type
    CHECK (item_type IN ('term', 'formula')),
  CONSTRAINT chk_exam_sheet_user_item_override_worked_example_mode
    CHECK (worked_example_mode IS NULL OR worked_example_mode IN ('auto', 'always', 'never'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_exam_sheet_user_item_override_unique
  ON tbl_exam_sheet_user_item_override(user_config_id, item_type, item_handle);
