-- Migration: Add question/answer tables for testing (quizzes)
-- Run after backup. Creates: tbl_question, tbl_answer, tbl_question_answer, tbl_formula_question
--
-- FK behavior: CASCADE for question/formula links so deletions clean up.
-- Exception: tbl_question_answer.answer_id -> tbl_answer uses RESTRICT so shared
-- answers (e.g. "True"/"False") cannot be deleted while still linked to questions.

-- ============================================================================
-- 1. tbl_question
-- ============================================================================

CREATE TABLE IF NOT EXISTS tbl_question (
  question_id     INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_type   VARCHAR(20) NOT NULL,
  stem            TEXT NOT NULL,
  parent_question_id INTEGER NULL,
  part_label      VARCHAR(10) NULL,
  display_order   INTEGER NOT NULL DEFAULT 0,
  explanation     TEXT NULL,
  created_at      TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_question_type_check CHECK (
    question_type IN ('multiple_choice', 'true_false', 'word_problem', 'multipart')
  ),
  CONSTRAINT tbl_question_parent_fkey
    FOREIGN KEY (parent_question_id) REFERENCES tbl_question(question_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_tbl_question_parent ON tbl_question(parent_question_id);
CREATE INDEX IF NOT EXISTS idx_tbl_question_type ON tbl_question(question_type);

COMMENT ON TABLE tbl_question IS 'Questions and multipart setups; parts link via parent_question_id.';

-- ============================================================================
-- 2. tbl_answer
-- ============================================================================

CREATE TABLE IF NOT EXISTS tbl_answer (
  answer_id       INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answer_text     TEXT NOT NULL,
  answer_numeric  DECIMAL(20, 6) NULL,
  created_at      TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE tbl_answer IS 'Reusable answer text (and optional numeric); correctness is per-question in tbl_question_answer.';

-- ============================================================================
-- 3. tbl_question_answer (links questions to answers; is_correct per question)
-- ============================================================================

CREATE TABLE IF NOT EXISTS tbl_question_answer (
  question_answer_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id     INTEGER NOT NULL,
  answer_id       INTEGER NOT NULL,
  is_correct      BOOLEAN NOT NULL DEFAULT false,
  display_order   INTEGER NOT NULL DEFAULT 0,
  created_at      TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_question_answer_question_fkey
    FOREIGN KEY (question_id) REFERENCES tbl_question(question_id) ON DELETE CASCADE,
  CONSTRAINT tbl_question_answer_answer_fkey
    FOREIGN KEY (answer_id) REFERENCES tbl_answer(answer_id) ON DELETE RESTRICT,
  CONSTRAINT tbl_question_answer_uniq UNIQUE (question_id, answer_id)
);

CREATE INDEX IF NOT EXISTS idx_tbl_question_answer_question ON tbl_question_answer(question_id);

COMMENT ON TABLE tbl_question_answer IS 'Links questions to answers; is_correct and display_order per question.';

-- ============================================================================
-- 4. tbl_formula_question (many-to-many: formula <-> question)
-- ============================================================================

CREATE TABLE IF NOT EXISTS tbl_formula_question (
  formula_question_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  formula_id       INTEGER NOT NULL,
  question_id      INTEGER NOT NULL,
  formula_question_is_primary BOOLEAN NOT NULL DEFAULT false,
  formula_question_rank INTEGER NULL,
  created_at       TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_formula_question_formula_fkey
    FOREIGN KEY (formula_id) REFERENCES tbl_formula(formula_id) ON DELETE CASCADE,
  CONSTRAINT tbl_formula_question_question_fkey
    FOREIGN KEY (question_id) REFERENCES tbl_question(question_id) ON DELETE CASCADE,
  CONSTRAINT tbl_formula_question_uniq UNIQUE (formula_id, question_id)
);

CREATE INDEX IF NOT EXISTS idx_tbl_formula_question_formula ON tbl_formula_question(formula_id);
CREATE INDEX IF NOT EXISTS idx_tbl_formula_question_question ON tbl_formula_question(question_id);

COMMENT ON TABLE tbl_formula_question IS 'Links formulas to questions; for multipart, link the parent (setup) question.';
