-- Catalog courses: admin-maintained list of pre-defined courses (like institutions).
-- Users can select from this list when adding a course; selected catalog courses may later
-- get default terms, formulas, questions, and exam sheet (copy on enroll).
-- Run after add_institution_course_tables.sql.

-- 1. tbl_catalog_course
CREATE TABLE IF NOT EXISTS tbl_catalog_course (
  catalog_course_id   INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_name         VARCHAR(255) NOT NULL,
  course_code         VARCHAR(50) NULL,
  institution_id      INTEGER NULL,
  course_handle       VARCHAR(100) NULL,
  created_at          TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_catalog_course_handle_uniq UNIQUE (course_handle),
  CONSTRAINT tbl_catalog_course_institution_fkey
    FOREIGN KEY (institution_id) REFERENCES tbl_institution(institution_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_tbl_catalog_course_handle ON tbl_catalog_course(course_handle);
CREATE INDEX IF NOT EXISTS idx_tbl_catalog_course_name ON tbl_catalog_course(course_name);
CREATE INDEX IF NOT EXISTS idx_tbl_catalog_course_institution ON tbl_catalog_course(institution_id);

COMMENT ON TABLE tbl_catalog_course IS 'Pre-defined courses (catalog); users can select when adding a course. Like institutions.';

-- 2. Add catalog_course_id to tbl_course (nullable; set when user adds course from catalog)
ALTER TABLE tbl_course
  ADD COLUMN IF NOT EXISTS catalog_course_id INTEGER NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'tbl_course_catalog_fkey'
  ) THEN
    ALTER TABLE tbl_course
      ADD CONSTRAINT tbl_course_catalog_fkey
      FOREIGN KEY (catalog_course_id) REFERENCES tbl_catalog_course(catalog_course_id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_tbl_course_catalog ON tbl_course(catalog_course_id);

COMMENT ON COLUMN tbl_course.catalog_course_id IS 'Set when course was created by selecting from catalog; NULL for user-created custom courses.';
