-- Guided learning (checkpoints, lesson variants/pages/blocks), user progress, sessions, activity events.
-- Run after add_segment_table_and_replace_segment_label.sql (tbl_segment exists).
-- Checkpoints are scoped by catalog segment only: segment_id -> tbl_segment (catalog_course_id is implicit).

-- ---------- Content ----------

CREATE TABLE IF NOT EXISTS tbl_checkpoint (
  checkpoint_id            INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  segment_id               INTEGER NOT NULL,
  checkpoint_title         VARCHAR(500) NOT NULL,
  checkpoint_description   TEXT NULL,
  checkpoint_order_index   INTEGER NOT NULL DEFAULT 0,
  is_required              BOOLEAN NOT NULL DEFAULT false,
  created_at               TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_checkpoint_segment_fkey
    FOREIGN KEY (segment_id) REFERENCES tbl_segment(segment_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_tbl_checkpoint_segment ON tbl_checkpoint(segment_id);
CREATE INDEX IF NOT EXISTS idx_tbl_checkpoint_segment_order ON tbl_checkpoint(segment_id, checkpoint_order_index);

COMMENT ON TABLE tbl_checkpoint IS 'Progression node within a catalog segment; optional lessons and/or question gate.';
COMMENT ON COLUMN tbl_checkpoint.segment_id IS 'FK to tbl_segment; catalog_course_id is derived via tbl_segment.catalog_course_id.';

CREATE TABLE IF NOT EXISTS tbl_lesson_variant (
  lesson_variant_id   INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  checkpoint_id       INTEGER NOT NULL,
  variant_label       VARCHAR(255) NOT NULL,
  variant_type        VARCHAR(32) NOT NULL,
  variant_order_index INTEGER NOT NULL DEFAULT 0,
  is_default          BOOLEAN NOT NULL DEFAULT false,
  created_at          TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_lesson_variant_checkpoint_fkey
    FOREIGN KEY (checkpoint_id) REFERENCES tbl_checkpoint(checkpoint_id) ON DELETE CASCADE,
  CONSTRAINT tbl_lesson_variant_type_chk
    CHECK (variant_type IN ('direct', 'quick', 'full', 'other'))
);

CREATE INDEX IF NOT EXISTS idx_tbl_lesson_variant_checkpoint ON tbl_lesson_variant(checkpoint_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tbl_lesson_variant_one_default
  ON tbl_lesson_variant(checkpoint_id) WHERE is_default = true;

CREATE TABLE IF NOT EXISTS tbl_lesson_page (
  lesson_page_id    INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_variant_id INTEGER NOT NULL,
  page_title        VARCHAR(500) NULL,
  page_order_index  INTEGER NOT NULL DEFAULT 0,
  created_at        TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_lesson_page_variant_fkey
    FOREIGN KEY (lesson_variant_id) REFERENCES tbl_lesson_variant(lesson_variant_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_tbl_lesson_page_variant ON tbl_lesson_page(lesson_variant_id);
CREATE INDEX IF NOT EXISTS idx_tbl_lesson_page_variant_order ON tbl_lesson_page(lesson_variant_id, page_order_index);

CREATE TABLE IF NOT EXISTS tbl_lesson_block (
  lesson_block_id     INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_page_id      INTEGER NOT NULL,
  block_type          VARCHAR(64) NOT NULL,
  block_content       JSONB NULL,
  block_order_index   INTEGER NOT NULL DEFAULT 0,
  linked_term_id      INTEGER NULL,
  linked_formula_id   INTEGER NULL,
  linked_question_id  INTEGER NULL,
  launch_mode         VARCHAR(32) NULL DEFAULT 'same_tab',
  media_asset_id      INTEGER NULL,
  created_at          TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_lesson_block_page_fkey
    FOREIGN KEY (lesson_page_id) REFERENCES tbl_lesson_page(lesson_page_id) ON DELETE CASCADE,
  CONSTRAINT tbl_lesson_block_term_fkey
    FOREIGN KEY (linked_term_id) REFERENCES tbl_term(term_id) ON DELETE SET NULL,
  CONSTRAINT tbl_lesson_block_formula_fkey
    FOREIGN KEY (linked_formula_id) REFERENCES tbl_formula(formula_id) ON DELETE SET NULL,
  CONSTRAINT tbl_lesson_block_question_fkey
    FOREIGN KEY (linked_question_id) REFERENCES tbl_question(question_id) ON DELETE SET NULL,
  CONSTRAINT tbl_lesson_block_launch_chk
    CHECK (launch_mode IS NULL OR launch_mode IN ('same_tab', 'new_tab', 'modal'))
);

CREATE INDEX IF NOT EXISTS idx_tbl_lesson_block_page ON tbl_lesson_block(lesson_page_id);
CREATE INDEX IF NOT EXISTS idx_tbl_lesson_block_page_order ON tbl_lesson_block(lesson_page_id, block_order_index);

-- Optional checkpoint-level question set (in addition to question-launch blocks)
CREATE TABLE IF NOT EXISTS tbl_checkpoint_question (
  checkpoint_id INTEGER NOT NULL,
  question_id   INTEGER NOT NULL,
  display_order INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT tbl_checkpoint_question_pk PRIMARY KEY (checkpoint_id, question_id),
  CONSTRAINT tbl_checkpoint_question_checkpoint_fkey
    FOREIGN KEY (checkpoint_id) REFERENCES tbl_checkpoint(checkpoint_id) ON DELETE CASCADE,
  CONSTRAINT tbl_checkpoint_question_question_fkey
    FOREIGN KEY (question_id) REFERENCES tbl_question(question_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_tbl_checkpoint_question_checkpoint ON tbl_checkpoint_question(checkpoint_id);

-- ---------- User progress ----------

CREATE TABLE IF NOT EXISTS tbl_user_checkpoint_path (
  user_checkpoint_path_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                 INTEGER NOT NULL,
  checkpoint_id           INTEGER NOT NULL,
  lesson_variant_id       INTEGER NULL,
  path_type               VARCHAR(32) NOT NULL,
  started_timestamp       TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  completed_timestamp     TIMESTAMP NULL,
  abandoned_timestamp     TIMESTAMP NULL,
  status                  VARCHAR(32) NOT NULL DEFAULT 'in_progress',
  CONSTRAINT tbl_user_checkpoint_path_user_fkey
    FOREIGN KEY (user_id) REFERENCES tbl_user(user_id) ON DELETE CASCADE,
  CONSTRAINT tbl_user_checkpoint_path_checkpoint_fkey
    FOREIGN KEY (checkpoint_id) REFERENCES tbl_checkpoint(checkpoint_id) ON DELETE CASCADE,
  CONSTRAINT tbl_user_checkpoint_path_variant_fkey
    FOREIGN KEY (lesson_variant_id) REFERENCES tbl_lesson_variant(lesson_variant_id) ON DELETE SET NULL,
  CONSTRAINT tbl_user_checkpoint_path_type_chk
    CHECK (path_type IN ('direct', 'quick', 'full', 'other')),
  CONSTRAINT tbl_user_checkpoint_path_status_chk
    CHECK (status IN ('in_progress', 'completed', 'abandoned'))
);

CREATE INDEX IF NOT EXISTS idx_tbl_user_checkpoint_path_user ON tbl_user_checkpoint_path(user_id);
CREATE INDEX IF NOT EXISTS idx_tbl_user_checkpoint_path_checkpoint ON tbl_user_checkpoint_path(checkpoint_id);
CREATE INDEX IF NOT EXISTS idx_tbl_user_checkpoint_path_variant ON tbl_user_checkpoint_path(lesson_variant_id);

CREATE TABLE IF NOT EXISTS tbl_user_lesson_progress (
  user_lesson_progress_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                 INTEGER NOT NULL,
  lesson_variant_id       INTEGER NOT NULL,
  current_page_id         INTEGER NULL,
  started_timestamp       TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  completed_timestamp     TIMESTAMP NULL,
  last_activity_timestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  status                  VARCHAR(32) NOT NULL DEFAULT 'in_progress',
  CONSTRAINT tbl_user_lesson_progress_user_fkey
    FOREIGN KEY (user_id) REFERENCES tbl_user(user_id) ON DELETE CASCADE,
  CONSTRAINT tbl_user_lesson_progress_variant_fkey
    FOREIGN KEY (lesson_variant_id) REFERENCES tbl_lesson_variant(lesson_variant_id) ON DELETE CASCADE,
  CONSTRAINT tbl_user_lesson_progress_page_fkey
    FOREIGN KEY (current_page_id) REFERENCES tbl_lesson_page(lesson_page_id) ON DELETE SET NULL,
  CONSTRAINT tbl_user_lesson_progress_status_chk
    CHECK (status IN ('in_progress', 'completed', 'abandoned'))
);

CREATE INDEX IF NOT EXISTS idx_tbl_user_lesson_progress_user ON tbl_user_lesson_progress(user_id);
CREATE INDEX IF NOT EXISTS idx_tbl_user_lesson_progress_variant ON tbl_user_lesson_progress(lesson_variant_id);

CREATE TABLE IF NOT EXISTS tbl_user_lesson_page_progress (
  user_lesson_page_progress_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                      INTEGER NOT NULL,
  lesson_page_id               INTEGER NOT NULL,
  first_opened_timestamp       TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  last_opened_timestamp        TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  completed_timestamp          TIMESTAMP NULL,
  estimated_seconds_on_page    INTEGER NULL,
  CONSTRAINT tbl_user_lesson_page_progress_user_fkey
    FOREIGN KEY (user_id) REFERENCES tbl_user(user_id) ON DELETE CASCADE,
  CONSTRAINT tbl_user_lesson_page_progress_page_fkey
    FOREIGN KEY (lesson_page_id) REFERENCES tbl_lesson_page(lesson_page_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_tbl_user_lesson_page_progress_user ON tbl_user_lesson_page_progress(user_id);
CREATE INDEX IF NOT EXISTS idx_tbl_user_lesson_page_progress_page ON tbl_user_lesson_page_progress(lesson_page_id);

-- ---------- Telemetry ----------

CREATE TABLE IF NOT EXISTS tbl_user_session (
  user_session_id           BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                   INTEGER NOT NULL,
  session_started_timestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  session_ended_timestamp   TIMESTAMP NULL,
  last_activity_timestamp   TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  estimated_active_seconds  INTEGER NULL,
  estimated_idle_seconds    INTEGER NULL,
  device_type               VARCHAR(64) NULL,
  user_agent                TEXT NULL,
  CONSTRAINT tbl_user_session_user_fkey
    FOREIGN KEY (user_id) REFERENCES tbl_user(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_tbl_user_session_user ON tbl_user_session(user_id);
CREATE INDEX IF NOT EXISTS idx_tbl_user_session_started ON tbl_user_session(session_started_timestamp);

CREATE TABLE IF NOT EXISTS tbl_user_activity_event (
  event_id           BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id            INTEGER NOT NULL,
  user_session_id    BIGINT NULL,
  event_type         VARCHAR(64) NOT NULL,
  route_name         VARCHAR(512) NULL,
  related_object_type VARCHAR(64) NULL,
  related_object_id  VARCHAR(64) NULL,
  event_timestamp    TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_user_activity_event_user_fkey
    FOREIGN KEY (user_id) REFERENCES tbl_user(user_id) ON DELETE CASCADE,
  CONSTRAINT tbl_user_activity_event_session_fkey
    FOREIGN KEY (user_session_id) REFERENCES tbl_user_session(user_session_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_tbl_user_activity_event_user ON tbl_user_activity_event(user_id);
CREATE INDEX IF NOT EXISTS idx_tbl_user_activity_event_type ON tbl_user_activity_event(event_type);
CREATE INDEX IF NOT EXISTS idx_tbl_user_activity_event_user_type ON tbl_user_activity_event(user_id, event_type);
CREATE INDEX IF NOT EXISTS idx_tbl_user_activity_event_timestamp ON tbl_user_activity_event(event_timestamp);
CREATE INDEX IF NOT EXISTS idx_tbl_user_activity_event_session ON tbl_user_activity_event(user_session_id);
