-- Migration: Add terms tables (parallel to formulas)
-- Creates: tbl_term, tbl_term_discipline, tbl_term_question
--
-- Terms store definitions (e.g. population, sample) and link to disciplines.
-- Questions (tbl_question, tbl_answer, tbl_question_answer) are reused.

-- ============================================================================
-- 1. tbl_term
-- ============================================================================

CREATE TABLE IF NOT EXISTS tbl_term (
  term_id         INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term_name       VARCHAR(200) NOT NULL,
  definition      TEXT NOT NULL,
  display_order   INTEGER NULL,
  created_at      TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tbl_term_display_order ON tbl_term(display_order);
CREATE INDEX IF NOT EXISTS idx_tbl_term_name ON tbl_term(term_name);

COMMENT ON TABLE tbl_term IS 'Terminology definitions (e.g. population, sample) for statistics and other disciplines.';

-- ============================================================================
-- 2. tbl_term_discipline (many-to-many: term <-> discipline)
-- ============================================================================

CREATE TABLE IF NOT EXISTS tbl_term_discipline (
  term_discipline_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term_id         INTEGER NOT NULL,
  discipline_id   INTEGER NOT NULL,
  term_discipline_is_primary BOOLEAN NOT NULL DEFAULT false,
  term_discipline_rank INTEGER NULL,
  created_at      TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_term_discipline_term_fkey
    FOREIGN KEY (term_id) REFERENCES tbl_term(term_id) ON DELETE CASCADE,
  CONSTRAINT tbl_term_discipline_discipline_fkey
    FOREIGN KEY (discipline_id) REFERENCES tbl_discipline(discipline_id) ON DELETE CASCADE,
  CONSTRAINT tbl_term_discipline_uniq UNIQUE (term_id, discipline_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tbl_term_discipline_one_primary
  ON tbl_term_discipline(term_id)
  WHERE term_discipline_is_primary = true;

CREATE INDEX IF NOT EXISTS idx_tbl_term_discipline_term ON tbl_term_discipline(term_id);
CREATE INDEX IF NOT EXISTS idx_tbl_term_discipline_discipline ON tbl_term_discipline(discipline_id);

COMMENT ON TABLE tbl_term_discipline IS 'Links terms to disciplines; many-to-many with primary/rank.';

-- ============================================================================
-- 3. tbl_term_question (many-to-many: term <-> question)
-- ============================================================================

CREATE TABLE IF NOT EXISTS tbl_term_question (
  term_question_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term_id         INTEGER NOT NULL,
  question_id     INTEGER NOT NULL,
  term_question_is_primary BOOLEAN NOT NULL DEFAULT false,
  term_question_rank INTEGER NULL,
  created_at      TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_term_question_term_fkey
    FOREIGN KEY (term_id) REFERENCES tbl_term(term_id) ON DELETE CASCADE,
  CONSTRAINT tbl_term_question_question_fkey
    FOREIGN KEY (question_id) REFERENCES tbl_question(question_id) ON DELETE CASCADE,
  CONSTRAINT tbl_term_question_uniq UNIQUE (term_id, question_id)
);

CREATE INDEX IF NOT EXISTS idx_tbl_term_question_term ON tbl_term_question(term_id);
CREATE INDEX IF NOT EXISTS idx_tbl_term_question_question ON tbl_term_question(question_id);

COMMENT ON TABLE tbl_term_question IS 'Links terms to questions; for multipart, link the parent (setup) question.';
