-- Import production formula data to local development database
-- Run with: PGPASSWORD=dev123 psql -d linguaformula -U dev_user -f import_production_formulas.sql

-- Clear existing data first (optional)
-- DELETE FROM formula;

-- Insert all production formulas
INSERT INTO formula (id, formula_name, latex, display_order, formula_description) VALUES
(34, 'Conservation of momentum', '\vec{p}_1 (initial) + \vec{p}_2 (initial) = \vec{p}_1 (final) + \vec{p}_2 (final)', 2, ''),
(35, 'Kinetic energy', 'E_{kinetic} = \frac{1}{2} m v^2', 3, ''),
(36, 'Potential energy', 'E_{potential} = m g h', 4, ''),
(2, 'Newton''s Second Law', 'F = ma', 5, ''),
(67, 'Euler''s Number', 'e = \lim_{n \to \infty} \left(1 + \frac{1}{n} \right)^n \approx 2.71828', 6, 'Euler''s number is the limit of (1 + 1/n)^n as n approaches infinity. It is approximately 2.71828 and is the base of natural logarithms.'),
(3, 'Mass-energy equivalence', 'E=mc^2', 6, ''),
(133, 'Size of Population (of Data)', 'n', 26, 'In statistics, the size of the population (or dataset) to be studied is represented by n. For example, if we intend to take samples from a bucket of 50 parts, n = 50.'),
(134, 'Size of a Sample (of Data)', 'r', 27, 'In statistics, the size of a sample to be taken from a larger population (or dataset) is represented by r. For example, if we take a sample of 5 parts from a bucket of parts, r = 5.'),
(135, 'Number of Ways to Arrange n Objects', 'n!', 28, 'In statistics and combinatorics, n! (n factorial) is the number of ways to arrange n objects in order. For example, if there are 5 playing cards (10, J, Q, K, Ace), they can be arranged in 5! = 120 ways, each representing a unique ordering.'),
(143, 'Permutations: Counting the Ways to Arrange r DISTINCT Objects Selected from n with No Replacement', 'P(n,r) = P_r^n = \frac{n!}{(n-r)!}', 29, 'In statistics and combinatorics, P(n,r) represents the number of ways to arrange r DISTINCT objects selected from a set of n, without replacement and where order matters. For example, P(52, 5) gives the number of ordered arrangements of all 5-cards sequences that can be drawn from a 52-card deck. Note that n! counts the number of ways to arrange all n objects, and dividing by (n-r)! removes the arrangements of the unselected (n - r) items. (Note that there is another formula for permutations where some of the objects selected are the same.)'),
(169, 'Permutations of n Objects with Repeated Types', 'N = \frac{n!}{n_1! \cdot n_2! \cdot ... \cdot n_r!}', 30, 'This formula is used to count how many ways there are to arrange all n objects when some are indistinguishable (repeated types). An example of this is counting unique arrangements of items with repetitions, such as the number of ways to arrange the letters in the word BALLOON. There are 7 total letters in BALLOON: 1 B, 1 A, 2 Ls, 2 Os, and 1 N. The number of ways to arrange these letters is: n! / (n1! * n2! * ... * nr!) = 7! / (1! * 1! * 2! * 2! * 1!) = 5040 / 4 = 1260'),
(142, 'Number of Ways to Choose from n with No Replacement and Order Does Not Matter', 'C(n,r) = \binom{n}{r} = \frac{n!}{r!(n-r)!}', 31, 'In statistics and combinatorics, C(n,r) represents the number of ways to chose r objects from a set of n, with no replacement and where order does not matter. For example, C(52, 5) gives the number of 5-card hands that can be drawn from a 52-card deck. Note that n! counts the number of ways to arrange all n objects, dividing by r! removes the permutations of the r selected objects since their order does not matter, and dividing by (n-r)! removes the permutations of the unselected objects, which are also irrelevant to the count.'),
(144, 'Sample Space: A Set of All Possible Outcomes', 'S', 35, 'In statistics, S typically represents the sample space – the set of all possible outcomes of an observation, experiment, or random process. The sample space is called "discrete" if it consists of a finite or countably infinite set of outcomes. It is called "continuous" if it includes an interval of real numbers. For example, a countably infinite sample space might be S = {1, 2, 3, ...}, since each element can be matched to a natural number. In contrast, a continuous sample space includes values such as all real numbers between 1 and 3. These values cannot be listed or assigned ordinal positions, because even between 0.001 and 0.002 there are infinitely many real numbers.'),
(145, 'Sample: Individual Outcome', 'x, s, \text{or } \omega', 36, 'In statistics, x, s, or ω (omega) may be used to represent individual outcomes of an experiment. The lowercase letter x is often used when outcomes are numeric; s represents a single outcome within sample space S; and ω is commonly used in probability theory. So if S = {a, b, c}, a single outcome (or element of the sample space) might be denoted: "Let s ∈ S" or "Let ω ∈ S"'),
(100, 'Positive Real Sample Space', 'S = \mathbb{R}^+ = \{x \mid x > 0\}', 40, 'The sample space S is the set of all positive real numbers — x such that x is greater than zero.'),
(146, 'Event', 'E', 45, 'In statistics, an event E is a subset of the sample space of a random experiment. An event consists of one or more outcomes from the sample space. For example, if a coin is flipped three times, the sample space is S = {HHH, THH, HTH, HHT, TTH, THT, HTT, TTT}. An event might be defined as all outcomes with exactly two heads: E = {THH, HTH, HHT}. This event contains 3 out of the 8 possible outcomes, so its probability is 3/8, or 0.375.'),
(148, 'Events – Union', 'E_1 \cup E_2', 46, 'The union of two events is the event that consists of all outcomes contained in either of the two joined events.'),
(149, 'Events – Intersection', 'E_1 \cap E_2', 47, 'The intersection of two events is the event that consists of all outcomes contained in both of the two joined events. When represented by a Venn diagram, it is the area where two circles overlap. In a SQL statement, an intersection is represented by the word AND in a WHERE clause.'),
(150, 'Event – Complement', 'E''', 48, 'The complement of an event in a sample space is the set of outcomes in the sample space that are not in the event. The complement of event E is E''.'),
(151, 'Events – Mutually Exclusive', 'A \cap B = \emptyset', 49, 'Two events, denoted as A and B that are mutually exclusive have a null (empty set) intersection.'),
(152, 'Double Complement Law', '(E'')'' = E', 50, 'Taking the complement of a complement returns the original set.'),
(154, 'Distributive Law of Intersection over Union', '(A \cup B) \cap C = (A \cap C) \cup (B \cap C)', 51, 'Intersection distributes over union. This is analogous to multiplication distributing over addition in algebra, as in C(A + B) = CA + CB. (See [link_to_come] for the structural, but not arithmetical, parallels between algebra and set operations.)'),
(157, 'Distributive Law of Union over Intersection', '(A \cap B) \cup C = (A \cup C) \cap (B \cup C)', 52, 'Union distributes over intersection. This mirrors the algebraic identity of (a x b) + c = (a + c)(b + c). (See [link_to_come] for the structural, but not arithmetical, parallels between algebra and set operations.)'),
(158, 'De Morgan''s Law (1)', '(A \cup B)'' = A'' \cap B''', 53, 'The complement of a union is the intersection of the complements.'),
(159, 'De Morgan''s Law (2)', '(A \cap B)'' = A'' \cup B''', 54, 'The complement of an intersection is the union of the complements.'),
(165, 'Multiplication Rule (for statistical counting techniques)', 'N = n_1 \times n_2 \times ... \times n_k', 55, 'If an operation consists of a sequence of steps, and each step can be completed in a fixed number of ways, then the total number of possible paths or outcomes of the whole operation is the product of the number of ways each step can be performed. This rule applies when each choice is independent of the previous ones. The total count N can also be visualized as the number of distinct paths through a branching decision process — one branch for each choice at each step. To give a simple example, imagine you have three shirts and two pairs of pants. You need to select one shirt and one pair of pants. Using the multiplication rule, the number of ways to select a shirt and pair of pants is 3 x 2 = 6.'),
(170, 'Probability of an Event', 'P(E)', 60, 'This is the general expression for the probability of an event E — that is, the chance that event E occurs. It is written as P(E).'),
(171, 'Probability of Equally Likely Outcomes', '\frac{1}{N}', 61, 'Whenever a sample space consists of N possible outcomes that are equally likely, the probability of each outcome is 1/N.'),
(172, 'Probability of Equally Likely Outcomes (2)', 'P(A) = \frac{\text{Number of favorable outcomes}}{\text{Total number of possible outcomes}} = \frac{s}{n}', 62, 'The probability of an event A is given by this formula, where s = number of outcomes where event A happens, and n = the total number of equally likely outcomes. For example, the odds of randomly selecting 1 laser diode from a batch of 100 is 1/100, or 0.01, where s = 1 and n = 100.'),
(176, 'Probability: Addition Rule for Discrete Probability', 'P(E) = P(a_1) + P(a_2) + ... + P(a_k)', 63, 'For a discrete sample space, the probability of an event E is the sum of the probabilities of the individual outcomes that make up the event. For example, suppose a random experiment can result in one of four outcomes: {a, b, c, d} with probabilities of P(a) = 0.1, P(b) = 0.3, P(c) = 0.3, P(d) = 0.1. Let the following events be defined as Event A = {a, b}, Event B = (b, c, d}, and Event C = {d}. The probability of Event A is calculated as P(A) = P(a) + P(b) = 0.1 + 0.3 = 0.4.'),
(177, 'Probability: Relative Frequency Approximation of Probability', 'P(A) = \frac{\text{number of times A occurred}}{\text{number of times the procedure repeated}}', 64, 'Conduct (or observe) a procedure and count the number of times that event A occurs. This formula approximates the probability of A.'),
(179, 'Probability: Addition Rule for Unions – Overlapping and Mutually Exclusive', 'P(A \cup B) = P(A) + P(B) - P(A \cap B)', 65, 'For the union of two overlapping events, add the probability of the two events and subtract the duplication. For mutually exclusive events, there is no need to subtract an intersection.'),
(181, 'Probability: Mutually Exclusive Events', 'A \cap B = \emptyset \text{ then } P(A \cap B) = 0', 66, 'The intersection of two mutually exclusive events is null, so the probability of that null intersection is zero.'),
(184, 'Probability: Conditional Events', 'P(B|A) = \frac{P(A \cap B)}{P(A)} = \frac{\text{# of outcomes in } A \cap B}{\text{# of outcomes in } A}', 67, 'This formula calculates the probability of event B occurring, given that event A has already occurred. The denominator, P(A), reflects that we are now working within a reduced sample space where A is known to have happened. The numerator, P(A ∩ B), represents the probability that both A and B occur — their joint probability. In simple cases, this may reduce to a ratio of counts, but the formula also accommodates more complex scenarios involving weighted probabilities or continuous probability distributions.'),
(185, 'Probability: Multiplication Rule for Conditional, Or Dependent, Events', 'P(A \cap B) = P(B \mid A) \cdot P(A) = P(A \mid B) \cdot P(B)', 68, 'This formula calculates the probability that two dependent events both occur. It is called the multiplication rule for conditional (or dependent) events. The key idea is that when one event affects the likelihood of another, we must adjust for that dependence. For example, if a bag contains 5 green marbles and 7 red marbles, the probability of drawing a green marble first is 5/12. After that draw, only 11 marbles remain, so the probability of drawing a red marble second becomes 7/11. The probability of drawing one green and one red marble in that order is (5/12) × (7/11). The formula also shows that the order of events can be reversed. If a red marble is selected first and a green marble second, the probability would be calculated as (7/12) × (5/11).'),
(187, 'Probability: Total Probability Rule (for Two Mutually Exclusive Events)', 'P(B) = P(B \cap A) + P(B \cap \overline{A}) = P(B \mid A) \cdot P(A) + P(B \mid \overline{A}) \cdot P(\overline{A})', 69, 'This formula expresses the total probability rule for two mutually exclusive and exhaustive events, A and its complement. It calculates the overall probability of an event B by summing its probabilities across distinct scenarios: when A occurs and when it does not. For example, suppose the probability of a silicon wafer failing is 0.1 when contamination is high and 0.005 when contamination is low. If the probability of high contamination is 0.2 and low contamination is 0.8, we can compute the total probability of failure by weighing each conditional probability by the likelihood of its condition: P(Failure) = P(Failure | High) × P(High) + P(Failure | Low) × P(Low) = 0.1 × 0.2 + 0.005 × 0.8 = 0.024.'),
(190, 'Probability: Success of Independent Series Components', 'P(L \cap R) = P(L) \cdot P(R)', 70, 'If two components in a series circuit operate independently, the probability that both components function successfully is the product of their individual probabilities. For example, if component L has a 0.8 probability of working and component R has a 0.9 probability of working, the probability that the entire series functions (i.e., both L and R work) is P(L) × P(R) = 0.8 × 0.9 = 0.72.'),
(191, 'Probability: Success of Independent Parallel Components', 'P(T \cup B) = P(T) + P(B) - P(T \cap B)', 71, 'If two components in a parallel circuit operate independently, the probability that at least one component functions successfully is calculated using the general addition rule: P(T ∪ B) = P(T) + P(B) − P(T ∩ B). For example, if component T has a 0.95 probability of working and component B has a 0.9 probability of working, the probability that at least one of them works is P(T) + P(B) − P(T ∩ B) = 0.95 + 0.9 − 0.855 = 0.995. (P(T ∩ B) = P(T) × P(B) = 0.855 due to independence.) This formula is not simply P(T) + P(B) because both components can succeed at the same time — their successful outcomes overlap. Adding P(T) and P(B) without subtracting the overlap would count those shared success cases twice. Subtracting P(T ∩ B) corrects for this and ensures each outcome is counted exactly once.'),
(192, 'Probability: Zero Contaminated Samples (Independent Trials)', 'P(\text{none contaminated}) = (1 - p)^n', 72, 'This formula calculates the probability that none of n independent samples are contaminated, where p is the probability that any single sample is contaminated. Because each sample is independent, the probability that each one avoids contamination is (1 - p), and the probability that all n avoid contamination is (1 - p)^n. For example, if the probability of high contamination is p = 0.11 and 5 samples are tested, the probability that none are contaminated is (0.89)^5 ≈ 0.5584.')
ON CONFLICT (id) DO NOTHING;

-- Update sequence to match highest ID
SELECT setval('formula_id_seq', (SELECT MAX(id) FROM formula));

-- Verify import
SELECT COUNT(*) as total_formulas FROM formula;
SELECT formula_name, display_order FROM formula ORDER BY display_order LIMIT 5;
